cover:
  height_scheme: full # full, half
  layout_scheme: focus # blank (留白), search (搜索), dock (坞), featured (精选), focus (焦点)

plugins:
  ################ required plugins ################
  # jquery
  globalJquery: false # 全局引入 jquery
  ################ optional plugins ################
  # issues api
  sitesjs:
    enable: true
  friendsjs:
    enable: true
  contributorsjs:
    enable: true

  ######## Plugins to improve loading speed:
  # 预加载
  preload:
    enable: true
    service: flying_pages # instant_page, flying_pages

  # 图片懒加载
  # https://www.npmjs.com/package/vanilla-lazyload
  # tips: 
  # 这里是主题自带的图片懒加载, 实现方案位于 /scripts/filters/z-lazyload ; srcset 属性的的优先级比 src 属性要高, 注意 srcset 存放了懒加载占位图,  src 存放了原图
  # 在支持 srcset 的浏览器或者 RSS 阅读器(还会有人使用老旧的阅读器?)上会优先读取 srcset 加载的图片(懒加载占位图), 对于 RSS 中图片丢失变成懒加载占位图的问题, 建议 自行使用脚本移除 srcset 属性 或 关闭图片懒加载 或 在 RSS 中插入 vanilla-lazyload
  lazyload:
    enable: true
    onlypost: false
    loadingImg:
    blurIn: true # 模糊加载效果 （loadingImg为空时有效）

  ######## Plugins to optimize the experience:
  # 代码高亮
  code_highlight: highlightjs # highlightjs or prismjs
  # highlight.js
  highlightjs:
    copy_code: true

  ######## Plugins for SEO:
  # npm i hexo-wordcount
  wordcount:
    enable: true

  ######## Plugins for ...
  # Button Ripple Effect
  nodewaves:
    enable: true

  # fontawesome V6:  https://fontawesome.com/docs/web/style/animate
  # fontawesome animation for fontawesome V5
  fontawesome_animation:
    enable: true

  # Typing Effects
  comment_typing:
    enable: true
  clipboard:
    enable: true
  fontawesome: volantis-static/libs/@fortawesome/fontawesome-pro/css/all.min.css
  parallax:
    enable: true
    position: fixed       # cover: sticky on the cover.   fixed: Fixed as background for the site.
    shuffle: false         # shuffle playlist
    duration: 30000       # Duration (ms)
    fade: 1500            # fade duration (ms) (Not more than 1500)
    images: # For personal use only. At your own risk if used for commercial purposes !!!
      - /bg/bg.webp
      - /bg/bg2.webp
      - /bg/bg3.webp
  busuanzi:
    enable: true
  aplayer:
    enable: true
    autoplay: false
    volume: 0.4
    order: random
    # id: 4917530132 # vol red
    # id: 4917524698 # vol blue
    # id: 76244489 # vol white
    # id: 5135845906 # for Volantis 3.0
    id: 5062959861 # TOP 30
  message:          # 音乐通知，播放、暂停、失败 时的图标
    enable: true
    icon:     # 默认图标，支持对图标添加颜色，可选值：see：/source/css/_plugins/message.styl
      default: fa-light fa-info-circle light-blue
      quection: fa-light fa-question-circle light-blue
    copyright:  # 是否在复制时弹出版权提示
      enable: false
      title: '知识共享许可协议'
      message: '请遵守 CC BY-NC-SA 4.0 协议。'
      icon: 'fa-brands fa-creative-commons light-blue'
    aplayer:
      enable: true
      play: fa-light fa-play light-blue
      pause: fa-light fa-pause light-blue
      error: fa-light fa-exclamation-square red
  darkmode:
    enable: true
  scrollreveal:
    enable: true
  pjax:
    enable: true
    cover: true          # 封面是否pjax处理 false：每次切换页面封面都重载，适合封面较少的情况 true：封面经过Pjax处理，适合封面较多的情况
    timeout: 5000        # The timeout in milliseconds for the XHR requests. Set to 0 to disable the timeout.
    cacheBust: false     # When set to true, Pjax appends a timestamp  to skip the browser cache.
    banUrl:              # 被屏蔽的 url 地址将不启用 pjax 跳转，可以在控制台下使用 window.location.pathname 获取
      # - '/artitalk/'   # artitalk 不支持 pjax
      # - '/bbtalk/'     # bbtalk 不支持 pjax
