cover:
  height_scheme: full # full, half
  layout_scheme: featured # blank (留白), search (搜索), dock (坞), featured (精选), focus (焦点)
  display:
    home: true
    archive: true
    others: false # can be written in front-matter 'cover: true'
  logo: # https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/blog/Logo-Cover@3x.png
  title: <h1 id="binft"></h1>
  search: 搜索... # search bar placeholder
  features:
    - name: 首页
      # img: volantis-static/media/twemoji/assets/svg/1f4eb.svg
      url: /
    - name: 文章
      # img: volantis-static/media/twemoji/assets/svg/1f4f0.svg #  https://cdn.jsdelivr.net/gh/twitter/twemoji@13.0/assets/svg/1f4f0.svg
      url: /archives/

scroll_smooth: true
dns_prefetch:
  - https://unpkg.com
  - https://cdn.bootcdn.net

############################### Comments ############################### > start
comments:
  title: <i class='fa-classic fa-comments'></i> 评论区
  subtitle:
  service: twikoo
  twikoo:
    path: # 全局评论地址
    envId: https://twikoo.hdilp.top/

plugins:
  ################ required plugins ################
  # jquery
  globalJquery: false # 全局引入 jquery
  ################ optional plugins ################
  # issues api
  sitesjs:
    enable: true
  friendsjs:
    enable: true
  contributorsjs:
    enable: true

  ######## Plugins to improve loading speed:
  # 预加载
  preload:
    enable: true
    service: flying_pages # instant_page, flying_pages

  # 图片懒加载
  # https://www.npmjs.com/package/vanilla-lazyload
  # tips: 
  # 这里是主题自带的图片懒加载, 实现方案位于 /scripts/filters/z-lazyload ; srcset 属性的的优先级比 src 属性要高, 注意 srcset 存放了懒加载占位图,  src 存放了原图
  # 在支持 srcset 的浏览器或者 RSS 阅读器(还会有人使用老旧的阅读器?)上会优先读取 srcset 加载的图片(懒加载占位图), 对于 RSS 中图片丢失变成懒加载占位图的问题, 建议 自行使用脚本移除 srcset 属性 或 关闭图片懒加载 或 在 RSS 中插入 vanilla-lazyload
  lazyload:
    enable: true
    onlypost: false
    loadingImg:
    blurIn: true # 模糊加载效果 （loadingImg为空时有效）

  ######## Plugins to optimize the experience:
  # 代码高亮
  code_highlight: highlightjs # highlightjs or prismjs
  # highlight.js
  highlightjs:
    copy_code: true

  ######## Plugins for SEO:
  # npm i hexo-wordcount
  wordcount:
    enable: true

  ######## Plugins for ...
  # Button Ripple Effect
  nodewaves:
    enable: true

  # fontawesome V6:  https://fontawesome.com/docs/web/style/animate
  # fontawesome animation for fontawesome V5
  fontawesome_animation:
    enable: true

  # Typing Effects
  comment_typing:
    enable: true
  clipboard:
    enable: true
  fontawesome: volantis-static/libs/@fortawesome/fontawesome-pro/css/all.min.css
  parallax:
    enable: true
    position: fixed       # cover: sticky on the cover.   fixed: Fixed as background for the site.
    shuffle: false         # shuffle playlist
    duration: 30000       # Duration (ms)
    fade: 1500            # fade duration (ms) (Not more than 1500)
    images: # For personal use only. At your own risk if used for commercial purposes !!!
      - /bg/1.webp
      - /bg/2.webp
      - /bg/3.webp
      - /bg/5.webp
      - /bg/6.webp
      - /bg/7.webp
      - /bg/8.webp
      - /bg/9.webp
      - /bg/10.webp
      - /bg/11.webp
      - /bg/12.webp
      - /bg/13.webp

  busuanzi:
    enable: true
  aplayer:
    enable: true
    autoplay: false
    volume: 0.4
    order: random
    # id: 4917530132 # vol red
    # id: 4917524698 # vol blue
    # id: 76244489 # vol white
    # id: 5135845906 # for Volantis 3.0
    id: 5062959861 # TOP 30
  message:          # 音乐通知，播放、暂停、失败 时的图标
    enable: true
    icon:     # 默认图标，支持对图标添加颜色，可选值：see：/source/css/_plugins/message.styl
      default: fa-light fa-info-circle light-blue
      quection: fa-light fa-question-circle light-blue
    copyright:  # 是否在复制时弹出版权提示
      enable: false
      title: '知识共享许可协议'
      message: '请遵守 CC BY-NC-SA 4.0 协议。'
      icon: 'fa-brands fa-creative-commons light-blue'
    aplayer:
      enable: true
      play: fa-light fa-play light-blue
      pause: fa-light fa-pause light-blue
      error: fa-light fa-exclamation-square red
  darkmode:
    enable: true
  scrollreveal:
    enable: true
  pjax:
    enable: true
    cover: true          # 封面是否pjax处理 false：每次切换页面封面都重载，适合封面较少的情况 true：封面经过Pjax处理，适合封面较多的情况
    timeout: 5000        # The timeout in milliseconds for the XHR requests. Set to 0 to disable the timeout.
    cacheBust: false     # When set to true, Pjax appends a timestamp  to skip the browser cache.
    banUrl:              # 被屏蔽的 url 地址将不启用 pjax 跳转，可以在控制台下使用 window.location.pathname 获取
      # - '/artitalk/'   # artitalk 不支持 pjax
      # - '/bbtalk/'     # bbtalk 不支持 pjax

custom_css:
  cursor:
    enable: true
    text: volantis-static/media/cursor/text.png
    pointer: volantis-static/media/cursor/pointer.png
    default: volantis-static/media/cursor/left_ptr.png
    not-allowed: volantis-static/media/cursor/circle.png
    zoom-out: volantis-static/media/cursor/zoom-out.png
    zoom-in: volantis-static/media/cursor/zoom-in.png
    grab: volantis-static/media/cursor/openhand.png
  font_smoothing: true # font-smoothing for webkit
  max_width: 1080px # Sum of body width and sidebar width (This limit will be exceeded when the device width is greater than 2000px, reaching 75% of the total width)
  scrollbar:
    size: 4px
    border: 2px
    background: rgb(255, 170, 178) linear-gradient(45deg, rgba(255, 255, 255, 0.4) 25%, transparent 25%, transparent 50%, rgba(255, 255, 255, 0.4) 50%, rgba(255, 255, 255, 0.4) 75%, transparent 75%, transparent)
    hover_background: rgb(255, 170, 178) linear-gradient(45deg, rgba(255, 255, 255, 0.4) 25%, transparent 25%, transparent 50%, rgba(255, 255, 255, 0.4) 50%, rgba(255, 255, 255, 0.4) 75%, transparent 75%, transparent)
  navbar:
    height: 64px
    width: max # auto, max
    effect: [shadow, floatable, blur] # [shadow, floatable, blur]
  sidebar:
    effect: [shadow, floatable, blur] # [shadow, floatable, blur]
  body:
    effect: [shadow, floatable, blur] # [shadow, floatable, blur]
    highlight:
      language: true # show language of codeblock
      grayscale: false # Enable grayscale effect
    text_align: # left, right, justify, center
      h1: left
      h2: left
      h3: left
      h4: left
      p: justify
  gap:
    h2: 48px # Spacing above H2 (only px unit)
    h3: 24px # Spacing above H3 (only px unit)
    h4: 16px # Spacing above H4 (only px unit)
    p: 1em # Paragraph spacing between paragraphs
    line_height: 1.6 # normal, 1.5, 1.75, 2 ...
  border_radius:
    card: 8px
    codeblock: 4px
    searchbar: 8px
    button: 4px
  fontsize:
    root: 16px
    h1: 1.5rem # 不推荐用在文章中
    h2: 1.5rem
    h3: 1.25rem
    h4: 1.125rem
    h5: 1rem
    h6: 1rem
    list: .9375rem
    meta: .875rem
    code: .8125rem
    footnote: .78125rem
  fontfamily:
    logofont:
      fontfamily: 'Dosis, "PingFang SC", "Microsoft YaHei", Helvetica, Arial'
      name: 'Dosis'
      url: /font/Dosis-Medium.ttf
      weight: normal
      style: normal
    bodyfont:
      fontfamily: '"DouyinSans", Dosis, "PingFang SC", "Microsoft YaHei", Helvetica, Arial'
      name: 'Dosis'
      url: /font/Dosis-Medium.ttf
      weight: normal
      style: normal

############################### Custom css ############################### > end
############################### Sidebar 文章侧边栏############################### > start
sidebar:
  position: right # left right
  # 主页、分类、归档等独立页面
  for_page: [blogger, category, tagcloud, webinfo]
  # layout: docs/post 这类文章页面
  for_post: [toc]
  # 侧边栏组件库
  widget_library:
    blogger:
      class: blogger
      display: [desktop, mobile] # [desktop, mobile]
      avatar: /avatar.png
      shape: circle # circle, rectangle
      url: /about/
      title: 砚海_Inkocean
      jinrishici: true # Poetry Today. You can set a string, and it will be displayed when loading fails.
      social:

    text:
      class: text
      display: [ desktop, mobile ]
      header:
        icon: fa-solid fa-bullhorn
        title: 公告
        url:
      content:
        - ''
    # toc widget (valid only in articles)
    toc:
      class: toc
      display: [desktop, mobile]
      sticky: true
      header:
        icon: fa-solid fa-list
        title: 本文目录
      list_number: false
      min_depth: 2
      max_depth: 5

    music:
      class: music
      display: [desktop, mobile]
      pjaxReload: false

    category:
      class: category
      display: [desktop, mobile]
      header:
        icon: fa-solid fa-folder-open
        title: 文章分类
        url: /categories/

    tagcloud:
      class: tagcloud
      display: [desktop]
      header:
        icon: fa-solid fa-tags
        title: 热门标签
        url: /tags/
      min_font: 14
      max_font: 24
      color: true
      start_color: '#999'
      end_color: '#555'

    webinfo:
      class: webinfo
      display: [desktop, mobile]
      header:
        icon: fa-solid fa-award
        title: 站点信息
      type:
        article:
          enable: true
          text: '文章数目：'
          unit: '篇'
        runtime:
          enable: true
          data: '2024/05/01'    # 填写建站日期
          text: '已运行时间：'
          unit: '天'
        wordcount:
          enable: true
          text: '本站总字数：'   # 需要启用 wordcount
          unit: '字'
        visitcounter:
          enable: true
          siteuv:
            text: '本站访客数：'
            unit: '人'
          sitepv:
            text: '本站总访问量：'
            unit: '次'
        lastupd:
          enable: true
          friendlyShow: true    # 更友好的时间显示
          text: '最后更新时间：'
          unit: ''

    lastupdate:
      class: lastupdate
      display: [desktop, mobile]
      header:
        icon: fa-duotonfa-clock WISTERIA
        title: 最近更新

############################### Sidebar ############################### > end
